### ISSUE TITLE
Not all users reported.

### ISSUE THREAD

**Issue by dragonsage00** [tgoetheyn/Export-NtfsSecurity#2]
Hello, I'm trying to run your power-shell script, but I keep getting some users. I am not getting all the domain users and I'm not getting everyone. I have set the domainusersonly to false and still not returning all the users I see on a folder when I look at the security tab of the folder.

**Comment by tgoetheyn** [comment]
Hi,
The scripts only searches for non-inherittet security.
Sometimes NTFS inheritance gets broken and only displays "parent folder" as "parent". In this case, set the 'CheckOrphanSecurity' parameter to $true

'everyone' is a special group without members, so maybe the script skips this (I should test this, as I wrote this quite a while ago)

**Comment by dragonsage00** [comment]
Thank you for the response. Is there a way to modify this script to list all the applied permissions? I like the option not to list out users for everyone or domain users, but I'm working on audit documentation and  this would really help me illustrate the complexity and issues with our shares to management, hopefully getting us the approval to correct the root cause.

**Comment by tgoetheyn** [comment]
if you want everything, just grab the security for all the subfolders where non-inherited permissions are set

```
  $analyzefolders = @()
  Get-ChildItem $unc -Recurse -Directory -Force -ErrorAction SilentlyContinue | % {
    $sec = get-acl $_.fullname | select -ExpandProperty SDDL
    if (($sec -like '*D:P*') -or ($sec -like '*A;OIIO;*') -or ($sec -like '*A;CI;*') -or $sec -like ("*A;OICI;*")){
      $analyzefolders += $_.fullname
    }
    $totalfolders++
  }
```

Then run everything through the `SuperSecuritySucker` :-)
don't forget to load the function and import the NTFSSecurity module
```
$dirs = @()
$analyzefolders | % {
  if ($_){
    try {
      $dirs += SuperSecuritySucker -path $_
    }catch{
      write-log "ERROR: cannot get security for $($_)"
    }
  }
}
```

then just output the `$dirs` variable

**Comment by dragonsage00** [comment]
Thank you, I'll give that a try this after noon. What is SuperSecuritySucker?

**Comment by tgoetheyn** [comment]
https://github.com/tgoetheyn/Export-NtfsSecurity/blob/master/Export-NtfsSecurity.ps1#L192

**Comment by dragonsage00** [comment]
=0) I should read a bit more, thank you for the assistance. I'll let you know when I get it working.

**Comment by tgoetheyn** [comment]
ok
